#!/bin/sh

# Acceder al directorio actual del script
cd "$(dirname "$0")"

# Add enviroment to Chatly
CHATLY_LIB="./usr/lib/chatly"
CHATLY_JAR="./Chatly.jar"
PATH=$PATH:$CHATLY_LIB/bin

# Mostrar informacion (testing) 
#echo .
#echo CHATLY_LIB : $CHATLY_LIB;
#echo CHATLY_JAR : $CHATLY_JAR;
#echo Ruta actual : $(pwd);
#echo "Ejecutar : " $CHATLY_LIB/bin/java -Xrs -jar $CHATLY_JAR
#echo .

# Run Chatly Jar
$CHATLY_LIB/bin/java -Xrs -jar $CHATLY_JAR
cd $(pwd)
