#!/bin/sh

# PATH run Chatly
CHLY_RUN=/opt/chatly/run.sh

# PATH Chatly BIN
CHLY_BIN=/usr/bin/chatly

# Create Chatly BIN
if [ -f "$CHLY_RUN" ]; then
    cp $CHLY_RUN $CHLY_BIN
    
    # Remove run Chatly
    if [ -f "$CHLY_BIN" ]; then
            rm $CHLY_RUN
    fi
    
    echo "chatly bin created success"
fi


